apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-publishing-house
  namespace: openshift-adp
spec:
  configuration:
    velero:
      defaultPlugins:
        - openshift
        - csi
        - aws
    nodeAgent:
      enable: true
      uploaderType: kopia   # file-level backup, portable across clusters/storage classes
  backupLocations:
    - velero:
        provider: aws
        default: true
        objectStorage:
          bucket: velero-backup-ad822aec-ca82-44d9-a146-a9a4afb59e8a
          prefix: velero
        config:
          region: us-east-1
          s3Url: https://s3.openshift-storage.svc:443
          s3ForcePathStyle: "true"
          insecureSkipTLSVerify: "true"
        credential:
          name: cloud-credentials
          key: cloud
