apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: publishing-house-nightly
  namespace: openshift-adp
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - publishing-house
    defaultVolumesToFsBackup: true
